### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Placeholder6** [SilentDemonSD/WZML-X#232]
**Is your feature request related to a problem? Please describe.**
i use a vps and dont like my ip being exposed in aria/qb peers, setting up proxies manually for them is a hassle, and Support for proxies on complete docker would be great.

**Describe the solution you'd like**
Some way to implement use of random proxies from a list, or at least a single proxy which is used for every connection by the bot

**Describe alternatives you've considered**
or a openvpn client to use vpns in the bot

**Additional context**
I legit got a dmca notice by mirroring some stuff through qbit, and was trying to add in proxies

**Comment by SilentDemonSD** [comment]
> **Is your feature request related to a problem? Please describe.** i use a vps and dont like my ip being exposed in aria/qb peers, setting up proxies manually for them is a hassle, and Support for proxies on complete docker would be great.
> 
> **Describe the solution you'd like** Some way to implement use of random proxies from a list, or at least a single proxy which is used for every connection by the bot
> 
> **Describe alternatives you've considered** or a openvpn client to use vpns in the bot
> 
> **Additional context** I legit got a dmca notice by mirroring some stuff through qbit, and was trying to add in proxies

Check docker-compose.yml to use VPN with gluten
