### ISSUE TITLE
/usr/bin/python3: No module named bot ( RIGHT UPSTREAM REPO & BRANCH )

### ISSUE THREAD

**Issue by ubranch** [SilentDemonSD/WZML-X#265]
/usr/bin/python3: No module named bot
 
 
# Update
UPSTREAM_REPO = "https://gitlab.com/mysterysd.sd/WZML-X"
UPSTREAM_BRANCH = "hk_wzmlx"
UPGRADE_PACKAGES = ""

**Comment by NamasteIndia** [comment]
use docker to deploy successfully make sure you are on Debian or Ubuntu 20

**Comment by SilentDemonSD** [comment]
> /usr/bin/python3: No module named bot
> 
> # Update
> UPSTREAM_REPO = "https://gitlab.com/mysterysd.sd/WZML-X" UPSTREAM_BRANCH = "hk_wzmlx" UPGRADE_PACKAGES = ""

Come to WZML-X Support at Telegram, Give Additional Details on Where you are trying on ...
